version: '2.0'

services:
  go:
    build: go
    image: dydx/go-micro
    ports:
      - "8001:8001"
  java:
    build: java
    image: dydx/java-micro
    ports:
      - "8002:8002"
  python:
    build: python
    image: dydx/python-micro
    ports:
      - "8003:8003"
